-- MySQL Script generated by MySQL Workbench
-- Sat Jul  6 23:55:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema informatica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema informatica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `informatica` DEFAULT CHARACTER SET utf8 ;
USE `informatica` ;


-- -----------------------------------------------------
-- Table `informatica`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `curso` INT NOT NULL,
  `seccion` INT NOT NULL,
  `especialidad` VARCHAR(20) NOT NULL,
  `ci` INT NOT NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Materia` (
  `id_materia` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Reporte` (
  `id_reporte` INT NOT NULL,
  `horario` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `Alumno_id_alumno` INT NOT NULL,
  `Materia_id_materia` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  INDEX `fk_Reporte_Alumno1_idx` (`Alumno_id_alumno` ASC),
  INDEX `fk_Reporte_Materia1_idx` (`Materia_id_materia` ASC) ,
  CONSTRAINT `fk_Reporte_Alumno1`
    FOREIGN KEY (`Alumno_id_alumno`)
    REFERENCES `informatica`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Materia1`
    FOREIGN KEY (`Materia_id_materia`)
    REFERENCES `informatica`.`Materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Rasgos_Conductuales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Rasgos_Conductuales` (
  `id_rasgo` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_rasgo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Detalle_Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Detalle_Reporte` (
  `Reporte_id_reporte` INT NOT NULL,
  `Rasgos Conductuales_id_rasgo` INT NOT NULL,
  PRIMARY KEY (`Reporte_id_reporte`, `Rasgos Conductuales_id_rasgo`),
  INDEX `fk_Reporte_has_Rasgos Conductuales_Rasgos Conductuales1_idx` (`Rasgos Conductuales_id_rasgo` ASC) ,
  INDEX `fk_Reporte_has_Rasgos Conductuales_Reporte_idx` (`Reporte_id_reporte` ASC) ,
  CONSTRAINT `fk_Reporte_has_Rasgos Conductuales_Reporte`
    FOREIGN KEY (`Reporte_id_reporte`)
    REFERENCES `informatica`.`Reporte` (`id_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_has_Rasgos Conductuales_Rasgos Conductuales1`
    FOREIGN KEY (`Rasgos Conductuales_id_rasgo`)
    REFERENCES `informatica`.`Rasgos_Conductuales` (`id_rasgo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Profesor` (
  `id_profesor` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Materia_por_Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Materia_por_Profesor` (
  `Materia_id_materia` INT NOT NULL,
  `Profesor_id_profesor` INT NOT NULL,
  PRIMARY KEY (`Materia_id_materia`, `Profesor_id_profesor`),
  INDEX `fk_Materia_has_Profesor_Profesor1_idx` (`Profesor_id_profesor` ASC) ,
  INDEX `fk_Materia_has_Profesor_Materia1_idx` (`Materia_id_materia` ASC),
  CONSTRAINT `fk_Materia_has_Profesor_Materia1`
    FOREIGN KEY (`Materia_id_materia`)
    REFERENCES `informatica`.`Materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Profesor_Profesor1`
    FOREIGN KEY (`Profesor_id_profesor`)
    REFERENCES `informatica`.`Profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Horario` (
  `id_horario` INT NOT NULL,
  `curso` INT NOT NULL,
  `seccion` INT NOT NULL,
  `especialidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informatica`.`Detalle_Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `informatica`.`Detalle_Horario` (
  `Horario_id_horario` INT NOT NULL,
  `Materia_id_materia` INT NOT NULL,
  `hora` TIME NOT NULL,
  `dia` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Horario_id_horario`, `Materia_id_materia`),
  INDEX `fk_Horario_has_Materia_Materia1_idx` (`Materia_id_materia` ASC) ,
  INDEX `fk_Horario_has_Materia_Horario1_idx` (`Horario_id_horario` ASC) ,
  CONSTRAINT `fk_Horario_has_Materia_Horario1`
    FOREIGN KEY (`Horario_id_horario`)
    REFERENCES `informatica`.`Horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_has_Materia_Materia1`
    FOREIGN KEY (`Materia_id_materia`)
    REFERENCES `informatica`.`Materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- --------------------------------------------------------



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
